from __future__ import annotations

from prometheus_client import Counter, Histogram

PROPOSAL_TOTAL = Counter(
    "trading_desk_proposals_total",
    "Trade Proposals generated by the lead analysts",
    ["ticker", "action"]
)

RISK_VERDICTS_TOTAL = Counter(
    "trading_desk_risk_verdicts_total",
    "Risk Engine Verdicts",
    ["approved", "resized"]
)

RISK_REJECTIONS_TOTAL = Counter(
    "trading_desk_risk_rejections_total",
    "Proposals rejected outright by the risk engine",
    ["ticker"]
)

HUMAN_DECISIONS_TOTAL = Counter(
    "trading_desk_human_decisions_total",
    "Human approve/reject decisions on risk-approved proposals",
    ["decision"],
)

APPROVAL_LATENCY_SECONDS = Histogram(
    "trading_desk_approval_latency_seconds",
    "Elapsed time between risk approval and the human decision being recorded",
    buckets=(1, 5, 15, 30, 60, 300, 900, 3600, 14400, 43200, 86400),
)

BROKER_ORDERS_TOTAL = Counter(
    "trading_desk_broker_orders_total",
    "Orders submitted to the broker, by execution mode and outcome",
    ["mode", "status"],
)